### ISSUE TITLE
Use Rspec for BDD and better documentation.

### ISSUE THREAD

**Issue by vivekimsit** [cleancodeexamples/elevator-simulation#1]
@aryehof I think it would be good to write tests in rspec, I have already added support for that. You can check it in my test branch f21479a.

**Comment by aryehof** [comment]
Frankly, I think it better to build a _working_ domain model that matches the _features_ required by this simple project, and use standard "test/unit" to verify those.  The existing implementation works, and could already be shown/verified working to a domain expert (if there was one).

**Comment by vivekimsit** [comment]
SGTM
